//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 CAD.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_CADTYPE                     130
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDD_SIZEDLG                     310
#define IDD_DIRDLG                      312
#define IDD_LAYOUTDLG                   314
#define IDB_SPLASH                      319
#define IDD_SPLASH                      320
#define IDD_PARAMETERDLG                322
#define IDD_PRINTERSETUPDLG             325
#define IDD_SENIORDLG                   327
#define IDD_SSPDLG                      329
#define IDD_SSDLG                       332
#define IDD_PRINTDLG                    335
#define IDB_BITMAP1                     338
#define IDD_VLTDLG                      339
#define IDB_PNG1                        349
#define IDD_FEEDBACK_DLG                357
#define IDD_VIPACC                      359
#define IDD_ML_SAVEBOX                  363
#define IDD_HOTKEY                      367
#define IDD_START                       369
#define IDD_PROPERTY_DEFINE             375
#define IDD_CBFILLDLG                   376
#define IDC_BUTTON1                     1000
#define IDC_BUTTON2                     1001
#define IDC_BUTTON3                     1002
#define IDC_BUTTON4                     1003
#define IDC_EDIT1                       1004
#define IDC_EDIT2                       1005
#define IDC_EDIT3                       1006
#define IDC_EDIT4                       1007
#define IDC_SPIN1                       1008
#define IDC_SPIN2                       1009
#define IDC_SPIN3                       1010
#define IDC_SPIN4                       1011
#define IDC_BUTTON5                     1012
#define IDC_BUTTON6                     1014
#define IDC_BUTTON7                     1015
#define IDC_BUTTON8                     1016
#define IDC_BUTTON9                     1017
#define IDC_BUTTON10                    1018
#define IDC_BUTTON11                    1019
#define IDC_BUTTON12                    1020
#define IDC_BUTTON_CBFILL				1021
#define IDC_LIST1                       1022
#define IDC_LIST2                       1023
#define IDC_LIST3                       1023
#define IDC_COMBO1                      1025
#define IDC_COMBO2                      1026
#define IDC_COMBO3                      1027
#define IDC_COMBO5                      1028
#define IDC_COMBO_SHAPE                 1028
#define IDC_MFCPROPERTYGRID1            1037
#define IDC_MFCBUTTON1                  1038
#define IDC_MFCBUTTON2                  1039
#define IDC_MFCBUTTON3                  1040
#define IDC_COMBO4                      1042
#define IDC_RADIO1                      1043
#define IDC_RADIO2                      1044
#define IDC_SLIDER1                     1046
#define IDC_SLIDER2                     1047
#define IDC_MFCBUTTON4                  1048
#define IDC_EDIT5                       1050
#define IDC_MFCEDITBROWSE1              1051
#define IDC_PROGRESS1                   1053
#define IDC_STATIC_FEEDBACK             1056
#define IDC_EDIT_FEEDBACK               1057
#define IDOK_GETTXT                     1058
#define IDC_VIP_ACC                     1059
#define IDC_VIP_PAS                     1060
#define IDC_START_STATIC                1061
#define IDC_CHECK1                      1062
#define IDC_RICHEDIT21                  1065
#define IDC_BUTTON_APPLY                1066
#define IDC_COMBO_CELLTYPE              1068
#define IDC_EDIT_CELLW                  1069
#define IDC_EDIT_CELL_L                 1070
#define IDC_EDIT_CELL_W                 1071
#define IDC_EDIT_CELL_H                 1072
#define IDC_CHECK_SQUARE                1073
#define IDC_EDIT_RADIAS_E               1074
#define IDC_EDIT_RADIAS_V               1075
#define IDC_CHECK_REMOVE_CANTILEVER     1076
#define IDC_CHECK_REMOVE_INDEPENDENT    1077
#define IDC_CHECK_PRJDIR                1078
#define IDC_EDIT_PL                     1080
#define IDC_EDIT_PW                     1081
#define ID_VIEW_PAN                     12000
#define ID_VIEW_ROTATE                  12001
#define ID_VIEW_ZOOM                    12002
#define ID_FILE_RECENTFILE              12003
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_EDIT_SELECTALL               32784
#define ID_EDIT_CANCELSEL               32785
#define ID_EDIT_DELETE                  32786
#define ID_EDIT_SIZE                    32788
#define ID_EDIT_DIR                     32789
#define ID_EDIT_STLMATERIAL             32790
#define ID_EDIT_SUPPORT                 32791
#define ID_PRINT_SET                    32796
#define ID_PRINT_INIT                   32798
#define ID_PRINT                        32800
#define ID_PRINT_PREVIEW                32802
#define ID_VIEW_ZOOMOUT                 32805
#define ID_VIEW_ZOOMIN                  32806
#define ID_VIEW_UP                      32809
#define ID_VIEW_BOTTOM                  32810
#define ID_VIEW_FRONT                   32811
#define ID_VIEW_REAR                    32813
#define ID_VIEW_LEFT                    32814
#define ID_VIEW_RIGHT                   32815
#define ID_VIEW_3D                      32816
#define ID_VIEW_FULL                    32826
#define ID_VIEW_ZOOMBOX                 32827
#define ID_INSERT_SUPPORT               32843
#define ID_INSERT_LAYOUT                32846
#define ID_VIEW_SECTION                 32852
#define ID_32853                        32853
#define ID_FILE_SSP                     32854
#define ID_EDIT1                        32856
#define ID_EDIT2                        32857
#define ID_COMBO1                       32858
#define ID_EDIT3                        32859
#define ID_EDIT_ROD                     32864
#define ID_VIEW_FULLWIN                 32865
#define ID_EDIT_DELSUPPORT              32866
#define ID_HELP_ABOUT                   32867
#define ID_HELP_SHORTCUTKEYS            32868
#define ID_HELP_CUSTOMSUPPORT           32869
#define ID_HELP_CUSTOMFEEDBACk          32870
#define ID_EDIT_                        32872
#define ID_EDIT_HEIGHT                  32872
#define ID_EDIT4                        32873
#define ID_BUTTON2                      32880
#define ID_SW_LANG                      32880
#define ID_SLIDER1                      32882
#define ID_EDIT5                        32883
#define ID_HELP_FEEDBACK                32884
#define ID_HELP_SUPPORT                 32885
#define ID_CHINESE                      32889
#define ID_ENGLISH                      32890
#define ID_BUTTON_DEF                   32893
#define ID_COMBO_DEF                    32894
#define ID_FILE_EXPORTSTL               33000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        374
#define _APS_NEXT_COMMAND_VALUE         32895
#define _APS_NEXT_CONTROL_VALUE         1082
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
